name: website

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
  pull_request:

env:
  JEKYLL_ENV: production

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for GitHub Pages deployment
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      -
        name: Build
        uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7.3.0
        with:
          targets: release
          set: |
            *.cache-from=type=gha,scope=website
            *.cache-to=type=gha,scope=website,mode=max
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Check GitHub Pages status
        if: github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-status@f0ef9e1cf727f9f76f8485f8c525fa03afc4ec02 # v5.0.0
        with:
          pages_threshold: major_outage
      -
        name: Deploy
        if: github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@1d6ee9b181a81033a16bd707a1401afa978daab4 # v5.0.0
        with:
          target_branch: master
          build_dir: web
          fqdn: portapps.io
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
